login:
    path:   /login
    defaults:  { _controller: Tom32iDemoBundle:Security:login }

login_check:
    path:   /login-check

logout:
    pattern:   /logout

tom32i_demo:
    resource: "@Tom32iDemoBundle/Controller/"
    type:     annotation
    prefix:   /